### ISSUE TITLE
Indicate WorldClim version in docs

### ISSUE THREAD

**Issue by plantarum** [rspatial/geodata#32]
Hi,

I'm starting to switch my code over to `geodata` from `raster::getData`. Comparing the data collected by each function, I was surprised that the layers didn't match - variables are recorded on different scales, with different extents, and different ranges.

After looking at the URLs for each function, I see now that `getData` downloads WorldClim version 1.4, and `worldclim_global` downloads version 2.1. Perhaps you could add this to the help page for `worldclim_global`? It might help others making the switch and finding the results of their analyses have changed.

Thanks all your work building and sharing these tools, they're indispensable for our work.

Best,

Tyler

**Comment by rhijmans** [comment]
I have added the version number to the docs. I have also added the version as an argument, but only "2.1" is supported. I could add "1.4", but that would be confusing because of the units (whether I keep them as they are, of change them to the same units as for "2.1"), so I am sure if I want to do that.

**Comment by plantarum** [comment]
Marvellous, thanks for the quick response!

I appreciate the confusion around units. Probably there will be little (and declining) interest in 1.4 moving forwards.
